"""add_tracked_developers_and_nullable_token

Revision ID: f489efe2148e
Revises: 77a7e8168423
Create Date: 2026-06-11 11:54:39.145386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f489efe2148e'
down_revision: Union[str, Sequence[str], None] = '77a7e8168423'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tracked_developers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('manager_id', sa.Integer(), nullable=False),
    sa.Column('developer_id', sa.Integer(), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['developer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['manager_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('manager_id', 'developer_id', name='uq_manager_developer')
    )
    with op.batch_alter_table('tracked_developers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tracked_developers_id'), ['id'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('access_token',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('access_token',
               existing_type=sa.VARCHAR(),
               nullable=False)

    with op.batch_alter_table('tracked_developers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tracked_developers_id'))

    op.drop_table('tracked_developers')
    # ### end Alembic commands ###
